"""add author field to post

Revision ID: 2ad72ef7281a
Revises: 84821c75adcb
Create Date: 2024-07-10 21:24:50.028236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ad72ef7281a"
down_revision: Union[str, None] = "84821c75adcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("author", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "author")
    # ### end Alembic commands ###
